import type { SFSqlHandoffOpportunity, SFSqlDashboardRecord } from './types'

function opp(partial: Partial<SFSqlHandoffOpportunity> & Pick<SFSqlHandoffOpportunity, 'Id' | 'Name' | 'OwnerId' | 'Owner.Name' | 'CreatedById' | 'CreatedBy.Name' | 'SQL_Date__c'>): SFSqlHandoffOpportunity {
  return {
    StageName: 'Qualifying',
    Initial_Meeting_Outcome__c: null,
    Initial_Meeting_FUp_Email_Status__c: null,
    Next_Meeting_Date__c: null,
    Last_Meeting_Date__c: null,
    LastActivityDate: null,
    NextStep: null,
    Discovery_Notes__c: null,
    AI_Last_Update__c: null,
    AI_Next_Steps__c: null,
    Manager_Review_Notes__c: null,
    Amount: null,
    CurrencyIsoCode: 'NZD',
    CloseDate: null,
    Record_Type_Name__c: 'New Subscription',
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    Metrics__c: 'Red', Metrics_Grade_Reason__c: null, Metric_Notes__c: null,
    Economic_Buyer__c: 'Red', Economic_Buyer_Grade_Notes__c: null, Economic_Buyer_Notes__c: null,
    Decision_Criteria__c: 'Red', Decision_Criteria_Grade_Reason__c: null, Decision_Criteria_Notes__c: null,
    Decision_Process__c: 'Red', Decision_Process_Grade_Reason__c: null, Decision_Process_Notes__c: null,
    Identified_Pain__c: 'Red', Identified_Pain_Grade_Reason__c: null, Identified_Pain_Notes__c: null,
    Champion__c: 'Red', Champion_Grade_Reason__c: null, Champion_Notes__c: null,
    Compelling_Event__c: 'Red', Compelling_Event_Grade_Notes__c: null, Compelling_Event_Notes__c: null,
    Competition__c: 'Red', Competition_Grade_Reason__c: null, Competition_Notes__c: null,
    ...partial,
  }
}

export const MOCK_SQL_HANDOFF_OPPORTUNITIES: SFSqlHandoffOpportunity[] = [
  opp({
    Id: '006Q900001rn6DJIAY', Name: 'Greater Atlanta Christian School - Expansion - CONTRACT RESET - 14/08/2026',
    OwnerId: 'own_james', 'Owner.Name': 'James Showers', CreatedById: 'usr_vp', 'CreatedBy.Name': 'Vincent Paget',
    SQL_Date__c: '2026-08-14', Record_Type_Name__c: 'Expansion (Mid-Term)', Amount: 34248.6, CloseDate: '2026-08-21',
  }),
  opp({
    Id: '006Q900001rnqKzIAI', Name: 'International School of Orange County - Attendance - 13/08/2026',
    OwnerId: 'own_warren', 'Owner.Name': 'Warren Griffiths', CreatedById: 'usr_kj', 'CreatedBy.Name': 'Kelly Jarvis',
    SQL_Date__c: '2026-08-13', Initial_Meeting_Outcome__c: 'No call detected', Next_Meeting_Date__c: '2026-08-18',
    AI_Last_Update__c: 'No relevant data found.', AI_Next_Steps__c: 'No next step confirmed.',
  }),
  opp({
    Id: '006Q900001rlA4zIAE', Name: 'Immaculate Conception Catholic Regional School - Attendance - 13/08/2026',
    OwnerId: 'own_aamer', 'Owner.Name': 'Aamer De', CreatedById: 'usr_aamer', 'CreatedBy.Name': 'Aamer De',
    SQL_Date__c: '2026-08-13',
  }),
  opp({
    Id: '006Q900001rgsplIAA', Name: 'St. Serra Catholic School - Attendance - 12/08/2026',
    OwnerId: 'own_kelly', 'Owner.Name': 'Kelly Jarvis', CreatedById: 'usr_kj', 'CreatedBy.Name': 'Kelly Jarvis',
    SQL_Date__c: '2026-08-12',
  }),
  opp({
    Id: '006Q900001rS7CQIA0', Name: 'St. Joan Antida High School - Emergencies - 11/08/2026',
    OwnerId: 'own_warren', 'Owner.Name': 'Warren Griffiths', CreatedById: 'usr_rb', 'CreatedBy.Name': 'Ramya Basavaraju',
    SQL_Date__c: '2026-08-11', Next_Meeting_Date__c: '2026-08-28',
    Discovery_Notes__c: 'PowerSchool is the SIS. Looking at new SIS options — keen to know what systems we integrate with. ~225 students, 1 campus.',
  }),
  opp({
    Id: '006Q900001rAV8LIAW', Name: 'Chartwell School - Attendance - 7/08/2026',
    OwnerId: 'own_warren', 'Owner.Name': 'Warren Griffiths', CreatedById: 'usr_kj', 'CreatedBy.Name': 'Kelly Jarvis',
    SQL_Date__c: '2026-08-07', Initial_Meeting_Outcome__c: 'No call detected', Next_Meeting_Date__c: '2026-08-26',
    AI_Last_Update__c: 'No relevant data found.', AI_Next_Steps__c: 'No next step confirmed.',
  }),
  opp({
    Id: '006Q900001qzdsPIAQ', Name: 'Charlotte Country Day School - Supervise - 10/08/2026',
    OwnerId: 'own_amanda', 'Owner.Name': 'Amanda Druker', CreatedById: 'usr_am', 'CreatedBy.Name': 'Ahad Mankar',
    SQL_Date__c: '2026-08-07', Initial_Meeting_Outcome__c: 'Held - interested', Last_Meeting_Date__c: '2026-08-12',
    LastActivityDate: '2026-08-13', NextStep: 'Send pricing proposal',
    Discovery_Notes__c: 'Independent JK–12 day school, ~1,800 students across two campuses. SIS: Veracross. Contact would be DM.',
    Economic_Buyer__c: 'Yellow', Economic_Buyer_Grade_Notes__c: 'EB not yet fully confirmed',
    Compelling_Event__c: 'Yellow', Compelling_Event_Grade_Notes__c: 'Budget window opening Q1',
  }),
  opp({
    Id: '006Q900001qorQrIAI', Name: 'Touchstone Community School - Attendance - 12/08/2026',
    OwnerId: 'own_james', 'Owner.Name': 'James Showers', CreatedById: 'usr_aamer', 'CreatedBy.Name': 'Aamer De',
    SQL_Date__c: '2026-08-06', Initial_Meeting_Outcome__c: 'Held - deferred', Last_Meeting_Date__c: '2026-08-13',
    LastActivityDate: '2026-08-13', NextStep: 'Email James with system functionality update',
  }),
  opp({
    Id: '006Q900001qRSBTIA4', Name: 'Holy Trinity School - Emergencies - 4/08/2026',
    OwnerId: 'own_amanda', 'Owner.Name': 'Amanda Druker', CreatedById: 'usr_rb', 'CreatedBy.Name': 'Ramya Basavaraju',
    SQL_Date__c: '2026-08-04', Last_Meeting_Date__c: '2026-08-05', LastActivityDate: '2026-08-05',
    Discovery_Notes__c: '550+ students, Preschool through 8th grade. SIS: FACTS.',
  }),
  opp({
    Id: '006Q900001q7cJpIAI', Name: 'Pioneer Valley Christian Academy - Attendance - 03/08/2026',
    OwnerId: 'own_james', 'Owner.Name': 'James Showers', CreatedById: 'usr_aamer', 'CreatedBy.Name': 'Aamer De',
    SQL_Date__c: '2026-08-01', Initial_Meeting_Outcome__c: 'Held - deferred', Last_Meeting_Date__c: '2026-08-05',
    LastActivityDate: '2026-08-05',
    Discovery_Notes__c: 'Dean of Students wants an early warning system to track and alert families on excessive absences and tardies.',
  }),
  opp({
    Id: '006Q900001mV9PRIA0', Name: 'Fulton Science Academy Private School - Attendance - 10/07/2026',
    OwnerId: 'own_james', 'Owner.Name': 'James Showers', CreatedById: 'usr_am', 'CreatedBy.Name': 'Ahad Mankar',
    SQL_Date__c: '2026-07-10', Initial_Meeting_Outcome__c: 'Held - deferred', Last_Meeting_Date__c: '2026-07-10',
    LastActivityDate: '2026-07-30', NextStep: null,
    Discovery_Notes__c: 'Pre-K–12, 973 students. SIS Blackbaud. Solving school visitor and student check in/out.',
  }),
  opp({
    Id: '006Q900001k6kRnIAI', Name: 'St. Francis Episcopal School - Supervise - 25/06/2026',
    OwnerId: 'own_paul', 'Owner.Name': 'Paul Organ', CreatedById: 'usr_sk', 'CreatedBy.Name': 'Sid Kannan',
    SQL_Date__c: '2026-06-25', Initial_Meeting_Outcome__c: 'Held - interested', Last_Meeting_Date__c: '2026-07-10',
    LastActivityDate: '2026-07-14', NextStep: 'Follow-up call with Paul (Head of Sales) and Warren.',
    Initial_Meeting_FUp_Email_Status__c: 'Sent - recap with recording', Amount: null, CloseDate: '2026-09-23',
    Metrics__c: 'Yellow', Economic_Buyer__c: 'Yellow', Economic_Buyer_Grade_Notes__c: 'CFO engaged, budget TBC',
    Compelling_Event__c: 'Yellow', Compelling_Event_Grade_Notes__c: 'Replacing legacy tools before next term',
    Manager_Review_Notes__c: 'Looks solid — make sure MEDDICC is fully graded before moving to Evaluation.',
  }),
  opp({
    Id: 'mock_ns_resched_01', Name: 'Riverside Prep Academy - Attendance - 05/08/2026',
    OwnerId: 'own_nick', 'Owner.Name': 'Nicholas Hillier', CreatedById: 'usr_sk', 'CreatedBy.Name': 'Sid Kannan',
    SQL_Date__c: '2026-08-01', Initial_Meeting_Outcome__c: 'No-show', Next_Meeting_Date__c: '2026-08-22',
  }),
  opp({
    Id: 'mock_ns_needs_01', Name: 'Lakeview Christian School - Attendance - 20/07/2026',
    OwnerId: 'own_alexis', 'Owner.Name': 'Alexis Gerlach', CreatedById: 'usr_ed', 'CreatedBy.Name': 'Emily DeRoche',
    SQL_Date__c: '2026-07-20', Initial_Meeting_Outcome__c: 'No-show',
  }),
  opp({
    Id: 'mock_not_interested_01', Name: 'Westbrook Country Day - Supervise - 02/07/2026',
    OwnerId: 'own_james', 'Owner.Name': 'James Showers', CreatedById: 'usr_aamer', 'CreatedBy.Name': 'Aamer De',
    SQL_Date__c: '2026-07-02', Initial_Meeting_Outcome__c: 'Held - not interested', Last_Meeting_Date__c: '2026-07-08',
    LastActivityDate: '2026-07-08', NextStep: 'Close out — not a fit right now',
  }),
  opp({
    Id: 'mock_disqualified_01', Name: 'Cedarwood Academy - Attendance - 15/06/2026',
    OwnerId: 'own_nick', 'Owner.Name': 'Nicholas Hillier', CreatedById: 'usr_nh', 'CreatedBy.Name': 'Nicholas Hillier',
    SQL_Date__c: '2026-06-15', Initial_Meeting_Outcome__c: 'Held - disqualified', Last_Meeting_Date__c: '2026-06-20',
    LastActivityDate: '2026-06-20', NextStep: 'No budget this fiscal year',
  }),
]

export const MOCK_NURTURING_OPPORTUNITIES: SFSqlHandoffOpportunity[] = [
  opp({
    Id: 'mock_nurture_overdue_01', Name: 'Brookfield Montessori School - Attendance - 20/06/2026',
    OwnerId: 'own_warren', 'Owner.Name': 'Warren Griffiths', CreatedById: 'usr_kj', 'CreatedBy.Name': 'Kelly Jarvis',
    SQL_Date__c: '2026-06-20', StageName: 'Nurturing', Initial_Meeting_Outcome__c: 'Held - deferred',
    Last_Meeting_Date__c: '2026-06-25', LastActivityDate: '2026-06-25',
    Re_engagement_Date__c: '2026-08-01', Nurturing_Reason__c: 'Waiting on new fiscal year budget before committing.',
    Economic_Buyer__c: 'Yellow', Compelling_Event__c: 'Yellow', NextStep: 'Check in once new budget is confirmed',
    Amount: 24500, CurrencyIsoCode: 'USD',
  }),
  opp({
    Id: 'mock_nurture_due30_01', Name: 'Harborview Academy - Supervise - 02/07/2026',
    OwnerId: 'own_james', 'Owner.Name': 'James Showers', CreatedById: 'usr_aamer', 'CreatedBy.Name': 'Aamer De',
    SQL_Date__c: '2026-07-02', StageName: 'Nurturing', Initial_Meeting_Outcome__c: 'Held - interested',
    Last_Meeting_Date__c: '2026-07-15', LastActivityDate: '2026-08-10',
    Re_engagement_Date__c: '2026-09-05', Nurturing_Reason__c: 'Board needs to sign off before renewing conversations.',
    Economic_Buyer__c: 'Green', Compelling_Event__c: 'Yellow', NextStep: 'Send updated proposal ahead of board meeting',
    Amount: 18200, CurrencyIsoCode: 'AUD',
  }),
  opp({
    Id: 'mock_nurture_due60_01', Name: 'Silverlake Preparatory - Attendance - 10/07/2026',
    OwnerId: 'own_amanda', 'Owner.Name': 'Amanda Druker', CreatedById: 'usr_am', 'CreatedBy.Name': 'Ahad Mankar',
    SQL_Date__c: '2026-07-10', StageName: 'Nurturing', Initial_Meeting_Outcome__c: 'Held - deferred',
    Last_Meeting_Date__c: '2026-07-18', LastActivityDate: '2026-07-22',
    Re_engagement_Date__c: '2026-10-05', Nurturing_Reason__c: 'Revisiting once their current SIS contract expires.',
    Economic_Buyer__c: 'Yellow', Compelling_Event__c: 'Yellow', Amount: 9800,
  }),
  opp({
    Id: 'mock_nurture_due90_01', Name: 'Oakridge Christian Academy - Emergencies - 15/07/2026',
    OwnerId: 'own_nick', 'Owner.Name': 'Nicholas Hillier', CreatedById: 'usr_nh', 'CreatedBy.Name': 'Nicholas Hillier',
    SQL_Date__c: '2026-07-15', StageName: 'Nurturing', Initial_Meeting_Outcome__c: 'Held - interested',
    Last_Meeting_Date__c: '2026-07-20', LastActivityDate: '2026-07-20',
    Re_engagement_Date__c: '2026-11-10', Nurturing_Reason__c: 'Circling back after their winter enrollment push.',
    Economic_Buyer__c: 'Yellow', Compelling_Event__c: 'Yellow',
  }),
  opp({
    Id: 'mock_nurture_due90plus_01', Name: 'Pinecrest Day School - Supervise - 01/07/2026',
    OwnerId: 'own_alexis', 'Owner.Name': 'Alexis Gerlach', CreatedById: 'usr_ed', 'CreatedBy.Name': 'Emily DeRoche',
    SQL_Date__c: '2026-07-01', StageName: 'Nurturing', Initial_Meeting_Outcome__c: 'Held - deferred',
    Last_Meeting_Date__c: '2026-07-08', LastActivityDate: '2026-07-08',
    Re_engagement_Date__c: '2027-01-15', Nurturing_Reason__c: 'Revisit at the start of next school year budgeting cycle.',
    Economic_Buyer__c: 'Green', Compelling_Event__c: 'Yellow',
  }),
  opp({
    Id: 'mock_nurture_nodate_01', Name: 'Maple Ridge International School - Attendance - 22/06/2026',
    OwnerId: 'own_kelly', 'Owner.Name': 'Kelly Jarvis', CreatedById: 'usr_kj', 'CreatedBy.Name': 'Kelly Jarvis',
    SQL_Date__c: '2026-06-22', StageName: 'Nurturing', Initial_Meeting_Outcome__c: 'Held - deferred',
    Last_Meeting_Date__c: '2026-06-28', LastActivityDate: '2026-06-28',
    Re_engagement_Date__c: null, Nurturing_Reason__c: 'Deprioritized after initial budget conversation stalled.',
    Economic_Buyer__c: 'Red', Compelling_Event__c: 'Red',
  }),
  opp({
    Id: 'mock_nurture_gaps_01', Name: 'Willowbrook School District - Expansion - 05/07/2026',
    OwnerId: 'own_paul', 'Owner.Name': 'Paul Organ', CreatedById: 'usr_sk', 'CreatedBy.Name': 'Sid Kannan',
    SQL_Date__c: '2026-07-05', StageName: 'Nurturing', Initial_Meeting_Outcome__c: 'Held - interested',
    Last_Meeting_Date__c: '2026-07-12', LastActivityDate: '2026-07-12',
    Re_engagement_Date__c: '2026-09-20', Nurturing_Reason__c: 'Champion left the district — rebuilding relationship.',
    Economic_Buyer__c: 'Red', Compelling_Event__c: 'Red',
  }),
]

export const MOCK_SQL_DASHBOARD_HISTORY: SFSqlDashboardRecord[] = [
  { Id: 'hist_001', OwnerId: 'own_alexis', 'Owner.Name': 'Alexis Gerlach', SQL_Date__c: '2026-07-28', SQO_Date__c: '2026-08-13', SQL_to_SQO_Days__c: 16, Net_ARR_NZD__c: 9131.90 },
  { Id: 'hist_002', OwnerId: 'own_warren', 'Owner.Name': 'Warren Griffiths', SQL_Date__c: '2026-07-08', SQO_Date__c: '2026-08-13', SQL_to_SQO_Days__c: 36, Net_ARR_NZD__c: 11211.27 },
  { Id: 'hist_003', OwnerId: 'own_amanda', 'Owner.Name': 'Amanda Druker', SQL_Date__c: '2026-07-22', SQO_Date__c: '2026-08-13', SQL_to_SQO_Days__c: 22, Net_ARR_NZD__c: 0 },
  { Id: 'hist_004', OwnerId: 'own_james', 'Owner.Name': 'James Showers', SQL_Date__c: '2026-07-16', SQO_Date__c: '2026-08-12', SQL_to_SQO_Days__c: 27, Net_ARR_NZD__c: 13060.74 },
  { Id: 'hist_005', OwnerId: 'own_warren', 'Owner.Name': 'Warren Griffiths', SQL_Date__c: '2026-08-07', SQO_Date__c: '2026-08-12', SQL_to_SQO_Days__c: 5, Net_ARR_NZD__c: 12277.10 },
  { Id: 'hist_006', OwnerId: 'own_nick', 'Owner.Name': 'Nicholas Hillier', SQL_Date__c: '2026-07-22', SQO_Date__c: '2026-08-11', SQL_to_SQO_Days__c: 20, Net_ARR_NZD__c: 4484.51 },
  { Id: 'hist_007', OwnerId: 'own_ed', 'Owner.Name': 'Emily DeRoche', SQL_Date__c: '2026-07-27', SQO_Date__c: '2026-08-06', SQL_to_SQO_Days__c: 10, Net_ARR_NZD__c: 18015.55 },
  { Id: 'hist_008', OwnerId: 'own_amanda', 'Owner.Name': 'Amanda Druker', SQL_Date__c: '2026-08-01', SQO_Date__c: '2026-08-05', SQL_to_SQO_Days__c: 4, Net_ARR_NZD__c: 40273.06 },
  { Id: 'hist_009', OwnerId: 'own_ed', 'Owner.Name': 'Emily DeRoche', SQL_Date__c: '2026-07-14', SQO_Date__c: '2026-07-30', SQL_to_SQO_Days__c: 3, Net_ARR_NZD__c: 25947.34 },
  { Id: 'hist_010', OwnerId: 'own_james', 'Owner.Name': 'James Showers', SQL_Date__c: '2026-07-16', SQO_Date__c: '2026-07-28', SQL_to_SQO_Days__c: 12, Net_ARR_NZD__c: 48997.94 },
  { Id: 'hist_011', OwnerId: 'own_warren', 'Owner.Name': 'Warren Griffiths', SQL_Date__c: '2026-07-15', SQO_Date__c: '2026-07-23', SQL_to_SQO_Days__c: 8, Net_ARR_NZD__c: 29256.06 },
  { Id: 'hist_012', OwnerId: 'own_nick', 'Owner.Name': 'Nicholas Hillier', SQL_Date__c: '2026-07-17', SQO_Date__c: '2026-07-20', SQL_to_SQO_Days__c: 3, Net_ARR_NZD__c: 1650.00 },
  // New SQLs this quarter that have NOT yet converted (no SQO_Date__c) — keeps SQL -> SQO % below 100%.
  { Id: 'hist_013', OwnerId: 'own_james', 'Owner.Name': 'James Showers', SQL_Date__c: '2026-08-14', SQO_Date__c: null, SQL_to_SQO_Days__c: null, Net_ARR_NZD__c: null },
  { Id: 'hist_014', OwnerId: 'own_warren', 'Owner.Name': 'Warren Griffiths', SQL_Date__c: '2026-08-13', SQO_Date__c: null, SQL_to_SQO_Days__c: null, Net_ARR_NZD__c: null },
  { Id: 'hist_015', OwnerId: 'own_aamer', 'Owner.Name': 'Aamer De', SQL_Date__c: '2026-08-13', SQO_Date__c: null, SQL_to_SQO_Days__c: null, Net_ARR_NZD__c: null },
  { Id: 'hist_016', OwnerId: 'own_kelly', 'Owner.Name': 'Kelly Jarvis', SQL_Date__c: '2026-08-12', SQO_Date__c: null, SQL_to_SQO_Days__c: null, Net_ARR_NZD__c: null },
  { Id: 'hist_017', OwnerId: 'own_amanda', 'Owner.Name': 'Amanda Druker', SQL_Date__c: '2026-08-07', SQO_Date__c: null, SQL_to_SQO_Days__c: null, Net_ARR_NZD__c: null },
  { Id: 'hist_018', OwnerId: 'own_alexis', 'Owner.Name': 'Alexis Gerlach', SQL_Date__c: '2026-08-06', SQO_Date__c: null, SQL_to_SQO_Days__c: null, Net_ARR_NZD__c: null },
  { Id: 'hist_019', OwnerId: 'own_nick', 'Owner.Name': 'Nicholas Hillier', SQL_Date__c: '2026-08-11', SQO_Date__c: null, SQL_to_SQO_Days__c: null, Net_ARR_NZD__c: null },
  { Id: 'hist_020', OwnerId: 'own_paul', 'Owner.Name': 'Paul Organ', SQL_Date__c: '2026-07-05', SQO_Date__c: null, SQL_to_SQO_Days__c: null, Net_ARR_NZD__c: null },
]
