import type { SFOpportunity, MockRepQuota } from './types'

// Owner IDs for mock reps
export const REP_IDS = {
  VINCENT: 'rep_vincent',
  JAMES: 'rep_james',
  WARREN: 'rep_warren',
  AAMER: 'rep_aamer',
  PAUL: 'rep_paul',
  KELLY: 'rep_kelly',
  GAGE: 'rep_gage',
  SID: 'rep_sid',
}

export const MOCK_OPPS: SFOpportunity[] = [
  // ── VINCENT's opps (5) ──────────────────────────────────────────────────

  // SQO - Evaluation: clean-ish
  {
    Id: 'opp_001',
    Name: 'Pinehurst School - New Subscription',
    AccountId: 'acc_001',
    'Account.Name': 'Pinehurst School',
    'Owner.Name': 'Vincent Paget',
    'Owner.Id': REP_IDS.VINCENT,
    StageName: 'Evaluation',
    Net_ARR__c: 38000,
    Net_ARR_NZD__c: 38000,
    CloseDate: '2026-06-15',
    Probability: 40,
    MEDDICC_Score__c: 55,
    Economic_Buyer__c: 'Green',
    Economic_Buyer_Grade_Notes__c: 'CFO confirmed as EB',
    Compelling_Event__c: 'Yellow',
    Compelling_Event_Grade_Notes__c: 'End of legacy contract Jul 26',
    Last_Meeting_Date__c: '2026-04-28',
    Next_Meeting_Date__c: '2026-05-20',
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: 'Product demo with IT team',
    CreatedDate: '2026-04-03',
    Current_Stage_Duration__c: 12,
  },

  // SQO - Proposal: missing EB
  {
    Id: 'opp_002',
    Name: 'Auckland Grammar School - New Subscription',
    AccountId: 'acc_002',
    'Account.Name': 'Auckland Grammar School',
    'Owner.Name': 'Vincent Paget',
    'Owner.Id': REP_IDS.VINCENT,
    StageName: 'Proposal',
    Net_ARR__c: 62000,
    Net_ARR_NZD__c: 62000,
    CloseDate: '2026-05-30',
    Probability: 60,
    MEDDICC_Score__c: 68,
    Economic_Buyer__c: 'Red',
    Economic_Buyer_Grade_Notes__c: 'EB not confirmed - dealing with HOD only',
    Compelling_Event__c: 'Green',
    Compelling_Event_Grade_Notes__c: 'Board approved budget in April',
    Last_Meeting_Date__c: '2026-05-01',
    Next_Meeting_Date__c: '2026-05-22',
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: 'Send revised proposal to Principal',
    CreatedDate: '2026-03-19',
    Current_Stage_Duration__c: 18,
  },

  // SQO - Negotiation: multiple flags
  {
    Id: 'opp_003',
    Name: "St Cuthbert's College - New Subscription",
    AccountId: 'acc_003',
    'Account.Name': "St Cuthbert's College",
    'Owner.Name': 'Vincent Paget',
    'Owner.Id': REP_IDS.VINCENT,
    StageName: 'Negotiation',
    Net_ARR__c: null,
    Net_ARR_NZD__c: null,
    CloseDate: '2026-05-28',
    Probability: 70,
    MEDDICC_Score__c: 72,
    Economic_Buyer__c: 'Green',
    Economic_Buyer_Grade_Notes__c: 'Principal is EB',
    Compelling_Event__c: 'Red',
    Compelling_Event_Grade_Notes__c: 'No clear deadline identified',
    Last_Meeting_Date__c: '2026-05-05',
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: 'Follow up on pricing approval',
    CreatedDate: '2026-03-07',
    Current_Stage_Duration__c: 22,
  },

  // SAO - Nurturing: missing re-engagement date
  {
    Id: 'opp_004',
    Name: 'Kristin School - New Subscription',
    AccountId: 'acc_004',
    'Account.Name': 'Kristin School',
    'Owner.Name': 'Vincent Paget',
    'Owner.Id': REP_IDS.VINCENT,
    StageName: 'Nurturing',
    Net_ARR__c: 24000,
    Net_ARR_NZD__c: 24000,
    CloseDate: '2026-09-30',
    Probability: 10,
    MEDDICC_Score__c: 20,
    Economic_Buyer__c: 'Yellow',
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: 'Red',
    Compelling_Event_Grade_Notes__c: 'No CE identified',
    Last_Meeting_Date__c: '2026-03-15',
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: 'Check back at start of Term 3',
    CreatedDate: '2026-02-17',
    Current_Stage_Duration__c: 60,
  },

  // SQL - Qualifying: Demo Scheduled
  {
    Id: 'opp_005',
    Name: 'Westlake Boys High School - New Subscription',
    AccountId: 'acc_005',
    'Account.Name': 'Westlake Boys High School',
    'Owner.Name': 'Vincent Paget',
    'Owner.Id': REP_IDS.VINCENT,
    StageName: 'Qualifying',
    Net_ARR__c: 45000,
    Net_ARR_NZD__c: 45000,
    CloseDate: '2026-06-30',
    Probability: 20,
    MEDDICC_Score__c: 25,
    Economic_Buyer__c: null,
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: null,
    Compelling_Event_Grade_Notes__c: null,
    Last_Meeting_Date__c: '2026-05-08',
    Next_Meeting_Date__c: '2026-05-21',
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: 'Discovery call booked',
    CreatedDate: '2026-04-28',
    Current_Stage_Duration__c: 20,
  },

  // ── JAMES SHOWERS ───────────────────────────────────────────────────────

  // SQO - Closing: clean, large deal
  {
    Id: 'opp_006',
    Name: 'Rangitoto College - New Subscription',
    AccountId: 'acc_006',
    'Account.Name': 'Rangitoto College',
    'Owner.Name': 'James Showers',
    'Owner.Id': REP_IDS.JAMES,
    StageName: 'Closing',
    Net_ARR__c: 78000,
    Net_ARR_NZD__c: 78000,
    CloseDate: '2026-05-25',
    Probability: 90,
    MEDDICC_Score__c: 88,
    Economic_Buyer__c: 'Green',
    Economic_Buyer_Grade_Notes__c: 'BOT chair signed off',
    Compelling_Event__c: 'Green',
    Compelling_Event_Grade_Notes__c: 'New academic year starting July',
    Last_Meeting_Date__c: '2026-05-10',
    Next_Meeting_Date__c: '2026-05-19',
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: 'Contract review with legal',
    CreatedDate: '2026-02-22',
    Current_Stage_Duration__c: 7,
    Type: 'New Subscription',
  },

  // SQO - Evaluation: pushed 4x
  {
    Id: 'opp_007',
    Name: 'Macleans College - New Subscription',
    AccountId: 'acc_007',
    'Account.Name': 'Macleans College',
    'Owner.Name': 'James Showers',
    'Owner.Id': REP_IDS.JAMES,
    StageName: 'Evaluation',
    Net_ARR__c: 29000,
    Net_ARR_NZD__c: 29000,
    CloseDate: '2026-05-31',
    Probability: 40,
    MEDDICC_Score__c: 38,
    Economic_Buyer__c: 'Yellow',
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: 'Yellow',
    Compelling_Event_Grade_Notes__c: null,
    Last_Meeting_Date__c: '2026-04-10',
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: 'Awaiting internal approval from Principal',
    CreatedDate: '2026-01-28',
    Current_Stage_Duration__c: 35,
  },

  // SQL - Qualifying: Demo Held, no follow-up
  {
    Id: 'opp_008',
    Name: 'Takapuna Grammar School - New Subscription',
    AccountId: 'acc_008',
    'Account.Name': 'Takapuna Grammar School',
    'Owner.Name': 'James Showers',
    'Owner.Id': REP_IDS.JAMES,
    StageName: 'Qualifying',
    Net_ARR__c: 18000,
    Net_ARR_NZD__c: 18000,
    CloseDate: '2026-06-30',
    Probability: 20,
    MEDDICC_Score__c: 22,
    Economic_Buyer__c: null,
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: null,
    Compelling_Event_Grade_Notes__c: null,
    Last_Meeting_Date__c: '2026-04-25',
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: null,
    CreatedDate: '2026-04-18',
    Current_Stage_Duration__c: 30,
  },

  // ── WARREN GRIFFITHS ────────────────────────────────────────────────────

  // SQO - Proposal: clean
  {
    Id: 'opp_009',
    Name: 'Epsom Girls Grammar - New Subscription',
    AccountId: 'acc_009',
    'Account.Name': 'Epsom Girls Grammar',
    'Owner.Name': 'Warren Griffiths',
    'Owner.Id': REP_IDS.WARREN,
    StageName: 'Proposal',
    Net_ARR__c: 54000,
    Net_ARR_NZD__c: 54000,
    CloseDate: '2026-06-10',
    Probability: 60,
    MEDDICC_Score__c: 64,
    Economic_Buyer__c: 'Green',
    Economic_Buyer_Grade_Notes__c: 'Deputy Principal confirmed EB',
    Compelling_Event__c: 'Green',
    Compelling_Event_Grade_Notes__c: 'Term 3 onboarding deadline',
    Last_Meeting_Date__c: '2026-05-02',
    Next_Meeting_Date__c: '2026-05-23',
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: 'Review proposal feedback',
    CreatedDate: '2026-03-24',
    Current_Stage_Duration__c: 14,
  },

  // SAO - Nurturing: re-engagement after close date
  {
    Id: 'opp_010',
    Name: 'Baradene College - New Subscription',
    AccountId: 'acc_010',
    'Account.Name': 'Baradene College',
    'Owner.Name': 'Warren Griffiths',
    'Owner.Id': REP_IDS.WARREN,
    StageName: 'Nurturing',
    Net_ARR__c: 19000,
    Net_ARR_NZD__c: 19000,
    CloseDate: '2026-06-30',
    Probability: 10,
    MEDDICC_Score__c: 15,
    Economic_Buyer__c: 'Yellow',
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: 'Yellow',
    Compelling_Event_Grade_Notes__c: 'Budget review in Q3',
    Last_Meeting_Date__c: '2026-03-20',
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: '2026-08-15',
    Nurturing_Reason__c: 'No budget this FY',
    NextStep: null,
    CreatedDate: '2026-03-04',
    Current_Stage_Duration__c: 55,
  },

  // SQL - Qualifying: No Demo
  {
    Id: 'opp_011',
    Name: 'ACG Parnell College - New Subscription',
    AccountId: 'acc_011',
    'Account.Name': 'ACG Parnell College',
    'Owner.Name': 'Warren Griffiths',
    'Owner.Id': REP_IDS.WARREN,
    StageName: 'Qualifying',
    Net_ARR__c: 32000,
    Net_ARR_NZD__c: 32000,
    CloseDate: '2026-06-30',
    Probability: 20,
    MEDDICC_Score__c: 10,
    Economic_Buyer__c: null,
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: null,
    Compelling_Event_Grade_Notes__c: null,
    Last_Meeting_Date__c: null,
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: 'Reach out to Head of Admin',
    CreatedDate: '2026-05-03',
    Current_Stage_Duration__c: 15,
  },

  // ── AAMER DE ────────────────────────────────────────────────────────────

  // SQO - Closing: no CE, pushed 3x
  {
    Id: 'opp_012',
    Name: 'Diocesan School for Girls - New Subscription',
    AccountId: 'acc_012',
    'Account.Name': 'Diocesan School for Girls',
    'Owner.Name': 'Aamer De',
    'Owner.Id': REP_IDS.AAMER,
    StageName: 'Closing',
    Net_ARR__c: 51000,
    Net_ARR_NZD__c: 51000,
    CloseDate: '2026-05-20',
    Probability: 90,
    MEDDICC_Score__c: 76,
    Economic_Buyer__c: 'Green',
    Economic_Buyer_Grade_Notes__c: 'Board approved',
    Compelling_Event__c: 'Red',
    Compelling_Event_Grade_Notes__c: 'Deadline unclear after scope change',
    Last_Meeting_Date__c: '2026-05-08',
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: 'Confirm final scope and pricing',
    CreatedDate: '2026-02-12',
    Current_Stage_Duration__c: 10,
  },

  // SAO - Nurturing: all four flags
  {
    Id: 'opp_013',
    Name: 'Wentworth College - New Subscription',
    AccountId: 'acc_013',
    'Account.Name': 'Wentworth College',
    'Owner.Name': 'Aamer De',
    'Owner.Id': REP_IDS.AAMER,
    StageName: 'Nurturing',
    Net_ARR__c: 14000,
    Net_ARR_NZD__c: 14000,
    CloseDate: '2026-06-30',
    Probability: 10,
    MEDDICC_Score__c: 8,
    Economic_Buyer__c: 'Red',
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: 'Red',
    Compelling_Event_Grade_Notes__c: null,
    Last_Meeting_Date__c: null,
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: null,
    CreatedDate: '2026-04-08',
    Current_Stage_Duration__c: 40,
  },

  // SQL - Qualifying: No Demo, stale
  {
    Id: 'opp_014',
    Name: 'Villa Education Trust - New Subscription',
    AccountId: 'acc_014',
    'Account.Name': 'Villa Education Trust',
    'Owner.Name': 'Aamer De',
    'Owner.Id': REP_IDS.AAMER,
    StageName: 'Qualifying',
    Net_ARR__c: 22000,
    Net_ARR_NZD__c: 22000,
    CloseDate: '2026-06-30',
    Probability: 20,
    MEDDICC_Score__c: 12,
    Economic_Buyer__c: null,
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: null,
    Compelling_Event_Grade_Notes__c: null,
    Last_Meeting_Date__c: null,
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: null,
    CreatedDate: '2026-04-20',
    Current_Stage_Duration__c: 28,
  },

  // ── KELLY JARVIS ────────────────────────────────────────────────────────

  // SQO - Evaluation: clean
  {
    Id: 'opp_015',
    Name: 'Marsden School - New Subscription',
    AccountId: 'acc_015',
    'Account.Name': 'Marsden School',
    'Owner.Name': 'Kelly Jarvis',
    'Owner.Id': REP_IDS.KELLY,
    StageName: 'Evaluation',
    Net_ARR__c: 17000,
    Net_ARR_NZD__c: 17000,
    CloseDate: '2026-06-20',
    Probability: 40,
    MEDDICC_Score__c: 50,
    Economic_Buyer__c: 'Green',
    Economic_Buyer_Grade_Notes__c: 'Principal engaged',
    Compelling_Event__c: 'Green',
    Compelling_Event_Grade_Notes__c: 'Replacing legacy system by July',
    Last_Meeting_Date__c: '2026-05-06',
    Next_Meeting_Date__c: '2026-05-27',
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: 'Technical evaluation call',
    CreatedDate: '2026-04-10',
    Current_Stage_Duration__c: 10,
  },

  // SQL - Qualifying: Demo Held, no follow-up
  {
    Id: 'opp_016',
    Name: 'Samuel Marsden Collegiate - New Subscription',
    AccountId: 'acc_016',
    'Account.Name': 'Samuel Marsden Collegiate',
    'Owner.Name': 'Kelly Jarvis',
    'Owner.Id': REP_IDS.KELLY,
    StageName: 'Qualifying',
    Net_ARR__c: 12000,
    Net_ARR_NZD__c: 12000,
    CloseDate: '2026-06-30',
    Probability: 20,
    MEDDICC_Score__c: 18,
    Economic_Buyer__c: null,
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: null,
    Compelling_Event_Grade_Notes__c: null,
    Last_Meeting_Date__c: '2026-04-30',
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: 'Send follow-up materials',
    CreatedDate: '2026-04-23',
    Current_Stage_Duration__c: 25,
  },

  // ── GAGE CRAWFORD ───────────────────────────────────────────────────────

  // SQO - Proposal: no EB
  {
    Id: 'opp_017',
    Name: 'Rosmini College - New Subscription',
    AccountId: 'acc_017',
    'Account.Name': 'Rosmini College',
    'Owner.Name': 'Gage Crawford',
    'Owner.Id': REP_IDS.GAGE,
    StageName: 'Proposal',
    Net_ARR__c: 35000,
    Net_ARR_NZD__c: 35000,
    CloseDate: '2026-06-15',
    Probability: 60,
    MEDDICC_Score__c: 58,
    Economic_Buyer__c: 'Red',
    Economic_Buyer_Grade_Notes__c: 'Not yet identified who controls budget',
    Compelling_Event__c: 'Green',
    Compelling_Event_Grade_Notes__c: 'New semester starting',
    Last_Meeting_Date__c: '2026-05-03',
    Next_Meeting_Date__c: '2026-05-24',
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: 'Identify and connect with budget holder',
    CreatedDate: '2026-03-29',
    Current_Stage_Duration__c: 16,
  },

  // SAO - Nurturing: no nurturing reason
  {
    Id: 'opp_018',
    Name: 'De La Salle College - New Subscription',
    AccountId: 'acc_018',
    'Account.Name': 'De La Salle College',
    'Owner.Name': 'Gage Crawford',
    'Owner.Id': REP_IDS.GAGE,
    StageName: 'Nurturing',
    Net_ARR__c: 28000,
    Net_ARR_NZD__c: 28000,
    CloseDate: '2026-09-30',
    Probability: 10,
    MEDDICC_Score__c: 22,
    Economic_Buyer__c: 'Yellow',
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: 'Yellow',
    Compelling_Event_Grade_Notes__c: 'Budget decision in Q4',
    Last_Meeting_Date__c: '2026-03-10',
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: '2026-07-01',
    Nurturing_Reason__c: null,
    NextStep: 'Re-engage in Term 3',
    CreatedDate: '2026-03-14',
    Current_Stage_Duration__c: 65,
  },

  // SQL - Qualifying: No Demo
  {
    Id: 'opp_019',
    Name: 'Liston College - New Subscription',
    AccountId: 'acc_019',
    'Account.Name': 'Liston College',
    'Owner.Name': 'Gage Crawford',
    'Owner.Id': REP_IDS.GAGE,
    StageName: 'Qualifying',
    Net_ARR__c: 8500,
    Net_ARR_NZD__c: 8500,
    CloseDate: '2026-06-30',
    Probability: 20,
    MEDDICC_Score__c: 8,
    Economic_Buyer__c: null,
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: null,
    Compelling_Event_Grade_Notes__c: null,
    Last_Meeting_Date__c: null,
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: 'Initial outreach pending',
    CreatedDate: '2026-05-08',
    Current_Stage_Duration__c: 10,
  },

  // ── CLOSED WON ──────────────────────────────────────────────────────────

  // Won: complete hygiene
  {
    Id: 'opp_020',
    Name: 'St Kentigern College - New Subscription',
    AccountId: 'acc_020',
    'Account.Name': 'St Kentigern College',
    'Owner.Name': 'James Showers',
    'Owner.Id': REP_IDS.JAMES,
    StageName: 'Closed Won',
    Net_ARR__c: 58000,
    Net_ARR_NZD__c: 58000,
    CloseDate: '2026-04-30',
    Probability: 100,
    MEDDICC_Score__c: null,
    Economic_Buyer__c: null,
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: null,
    Compelling_Event_Grade_Notes__c: null,
    Last_Meeting_Date__c: null,
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: null,
    CreatedDate: '2026-01-01',
    Current_Stage_Duration__c: null,
    Alternatives_Considered__c: 'Schoology and Google Classroom',
    Why_did_they_choose_us__c: 'Best product fit — onboarding integration was key differentiator',
    What_can_we_do_to_repeat_this_outcome__c: 'Lead with onboarding story in similar schools',
  },

  // Won: complete hygiene
  {
    Id: 'opp_021',
    Name: 'Pakuranga College - New Subscription',
    AccountId: 'acc_021',
    'Account.Name': 'Pakuranga College',
    'Owner.Name': 'Vincent Paget',
    'Owner.Id': REP_IDS.VINCENT,
    StageName: 'Closed Won',
    Net_ARR__c: 32000,
    Net_ARR_NZD__c: 32000,
    CloseDate: '2026-04-25',
    Probability: 100,
    MEDDICC_Score__c: null,
    Economic_Buyer__c: null,
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: null,
    Compelling_Event_Grade_Notes__c: null,
    Last_Meeting_Date__c: null,
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: null,
    CreatedDate: '2026-01-01',
    Current_Stage_Duration__c: null,
    Alternatives_Considered__c: 'Canvas LMS',
    Why_did_they_choose_us__c: 'Competitive pricing and ease of implementation',
    What_can_we_do_to_repeat_this_outcome__c: 'Emphasise implementation speed in proposals',
  },

  // Won: missing all 3 hygiene fields
  {
    Id: 'opp_022',
    Name: "King's School - New Subscription",
    AccountId: 'acc_022',
    'Account.Name': "King's School",
    'Owner.Name': 'Warren Griffiths',
    'Owner.Id': REP_IDS.WARREN,
    StageName: 'Closed Won',
    Net_ARR__c: 47000,
    Net_ARR_NZD__c: 47000,
    CloseDate: '2026-05-05',
    Probability: 100,
    MEDDICC_Score__c: null,
    Economic_Buyer__c: null,
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: null,
    Compelling_Event_Grade_Notes__c: null,
    Last_Meeting_Date__c: null,
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: null,
    CreatedDate: '2026-01-01',
    Current_Stage_Duration__c: null,
    Alternatives_Considered__c: null,
    Why_did_they_choose_us__c: null,
    What_can_we_do_to_repeat_this_outcome__c: null,
  },

  // ── CLOSED LOST ─────────────────────────────────────────────────────────

  // Lost: complete hygiene
  {
    Id: 'opp_023',
    Name: 'Botany Downs Secondary - New Subscription',
    AccountId: 'acc_023',
    'Account.Name': 'Botany Downs Secondary',
    'Owner.Name': 'Aamer De',
    'Owner.Id': REP_IDS.AAMER,
    StageName: 'Closed Lost',
    Net_ARR__c: 22000,
    Net_ARR_NZD__c: 22000,
    CloseDate: '2026-05-01',
    Probability: 0,
    MEDDICC_Score__c: null,
    Economic_Buyer__c: null,
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: null,
    Compelling_Event_Grade_Notes__c: null,
    Last_Meeting_Date__c: null,
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: null,
    CreatedDate: '2026-01-01',
    Current_Stage_Duration__c: null,
    Loss_Reason__c: 'No decision',
    Loss_Reason_Detail__c: 'Budget freeze announced — project deferred to FY27',
    Lost_From_Stage__c: 'Proposal',
  },

  // Lost: missing all hygiene fields
  {
    Id: 'opp_024',
    Name: 'Lynfield College - New Subscription',
    AccountId: 'acc_024',
    'Account.Name': 'Lynfield College',
    'Owner.Name': 'Kelly Jarvis',
    'Owner.Id': REP_IDS.KELLY,
    StageName: 'Closed Lost',
    Net_ARR__c: 15000,
    Net_ARR_NZD__c: 15000,
    CloseDate: '2026-05-08',
    Probability: 0,
    MEDDICC_Score__c: null,
    Economic_Buyer__c: null,
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: null,
    Compelling_Event_Grade_Notes__c: null,
    Last_Meeting_Date__c: null,
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: null,
    CreatedDate: '2026-01-01',
    Current_Stage_Duration__c: null,
    Loss_Reason__c: null,
    Loss_Reason_Detail__c: null,
    Lost_From_Stage__c: null,
  },

  // Lost: missing detail and stage
  {
    Id: 'opp_025',
    Name: 'Onehunga High School - New Subscription',
    AccountId: 'acc_025',
    'Account.Name': 'Onehunga High School',
    'Owner.Name': 'Gage Crawford',
    'Owner.Id': REP_IDS.GAGE,
    StageName: 'Closed Lost',
    Net_ARR__c: 18000,
    Net_ARR_NZD__c: 18000,
    CloseDate: '2026-05-10',
    Probability: 0,
    MEDDICC_Score__c: null,
    Economic_Buyer__c: null,
    Economic_Buyer_Grade_Notes__c: null,
    Compelling_Event__c: null,
    Compelling_Event_Grade_Notes__c: null,
    Last_Meeting_Date__c: null,
    Next_Meeting_Date__c: null,
    Re_engagement_Date__c: null,
    Nurturing_Reason__c: null,
    NextStep: null,
    CreatedDate: '2026-01-01',
    Current_Stage_Duration__c: null,
    Loss_Reason__c: 'Chose competitor',
    Loss_Reason_Detail__c: null,
    Lost_From_Stage__c: null,
  },
]

export const MOCK_REP_QUOTAS: MockRepQuota[] = [
  { repId: REP_IDS.VINCENT, repName: 'Vincent Paget', quota: 350000 },
  { repId: REP_IDS.JAMES, repName: 'James Showers', quota: 400000 },
  { repId: REP_IDS.WARREN, repName: 'Warren Griffiths', quota: 320000 },
  { repId: REP_IDS.AAMER, repName: 'Aamer De', quota: 280000 },
  { repId: REP_IDS.PAUL, repName: 'Paul Organ', quota: null },
  { repId: REP_IDS.KELLY, repName: 'Kelly Jarvis', quota: 250000 },
  { repId: REP_IDS.GAGE, repName: 'Gage Crawford', quota: 300000 },
  { repId: REP_IDS.SID, repName: 'Sid Kannan', quota: 220000 },
]
